### ISSUE TITLE
Allegedly Invalid API Key

### ISSUE THREAD

**Issue by MAGomes95** [comet-ml/comet-sdk-extensions#3]
Honestly do not know if I open the issue in the correct comet-ml repository, but bellow I describe my situation.

I am building an application that ultimately predicts the likelihood of a given person to develop lung cancer given a set of features. In order to deploy my application as a API, I am using Cerebrium.

In the moment of deploying the endpoint, more precisely, in the building phase, the process is interrupted with the following log:

File "/persistent-storage/.venv/miniconda/envs/lungcancer-svm/lib/python3.10/site-packages/comet_ml/connection.py", line 1985, in get

raise InvalidRestAPIKey(self.api_key)  # probably

comet_ml.exceptions.InvalidRestAPIKey: "xxxxxxxxxxxxxxxxxxxxx"

I have changed the API Key in comet-ml several times as well update its value in the secrets section of Cerebrium, so I know this is not the issue.

Could someone please help me understand why this is happening? 

Thank You!

**Comment by dsblank** [comment]
Yeah, you're in the wrong place :) Head over to https://github.com/comet-ml/issue-tracking or look us up on Slack: cometml.slack.com
